// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <WiFi.h>

const char DEVICE_LOGIN_NAME[]  = "ARDUINO_LOGIN_NAME";

const char SSID[]               = "MY_NET";    // Network SSID (name)
const char PASS[]               = "PASSWORD";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "ARDUINO_KEY";    // Secret device password



float mlx_temperatura = 0;
int pulse_sensor_bpm =0;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(mlx_temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pulse_sensor_bpm, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
