// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <WiFi.h>

const char DEVICE_LOGIN_NAME[]  = "1cb983e3-45bf-46db-bdeb-bd64ad171e4f";

const char SSID[]               = "NETLIFE-LIMA";    // Network SSID (name)
const char PASS[]               = "0932144009";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "HKAUMwudpjRsq5Oq4NHD@s#eb";    // Secret device password



float mlx_temperatura = 0;
int pulse_sensor_bpm =0;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(mlx_temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pulse_sensor_bpm, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);